ALTER TABLE `eurofarma`.`usuarios` 
CHANGE COLUMN `id` `id` BIGINT NOT NULL AUTO_INCREMENT FIRST,
CHANGE COLUMN `email` `email` VARCHAR(180) NULL DEFAULT NULL AFTER `id`,
CHANGE COLUMN `senha` `senha` VARCHAR(180) NOT NULL AFTER `email`;
